name: image_downloader
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get_it: ^7.6.4
  dio: ^5.3.3
  pretty_dio_logger: ^1.3.1
  flutter_bloc: ^8.1.3
  flutter_screenutil: ^5.9.0
  go_router: ^14.2.0
  shared_preferences: ^2.2.1
  flutter_native_splash: ^2.3.2
  permission_handler: ^11.3.1
  equatable: ^2.0.5
  flutter_svg: ^2.0.7
  lottie: ^3.1.2
  flutter_launcher_icons: ^0.13.1
  internet_connection_checker_plus: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter_family/Inter-ExtraLight.ttf
          weight: 100
    - family: Inter
      fonts:
        - asset: assets/fonts/inter_family/Inter-Light.ttf
          weight: 200
    - family: Inter
      fonts:
        - asset: assets/fonts/inter_family/Inter-Regular.ttf
          weight: 300
          style: normal
    - family: Inter
      fonts:
        - asset: assets/fonts/inter_family/Inter-Medium.ttf
          weight: 400
    - family: Inter
      fonts:
        - asset: assets/fonts/inter_family/Inter-SemiBold.ttf
          weight: 500
    - family: Inter
      fonts:
        - asset: assets/fonts/inter_family/Inter-Bold.ttf
          weight: 600
    - family: Inter
      fonts:
        - asset: assets/fonts/inter_family/Inter-ExtraBold.ttf
          weight: 700


